# Generated by Django 4.1.2 on 2023-01-04 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_user_id_following_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='following',
        ),
        migrations.RemoveField(
            model_name='following',
            name='folowing_id',
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='network.post'),
        ),
    ]
